mysql:
  container_name: mysql
  image: mysql
  ports:
    - 3306:3306
  volumes:
    - ./sql:/root/
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=init123!!
    - MYSQL_DATABASE=ejabberd
#ejabberd:
#  container_name: ejabberd
#  image: rroemhild/ejabberd
#  ports:
#    - 5222:5222
#    - 5269:5269
#    - 5280:5280
#  links:
#    - mysql:mysql
#  environment:
#    - ERLANG_NODE=ejabberd
#    - XMPP_DOMAIN=localhost
#    - EJABBERD_ADMINS=admin@localhost
#    - EJABBERD_USERS=admin@localhost:init123!! ktz@localhost:init123!!
#    - EJABBERD_HTTPS=false
#    - EJABBERD_STARTTLS=false
#    - EJABBERD_AUTH_METHOD=external
#    - EJABBERD_EXTAUTH_PROGRAM=/opt/ejabberd/scripts/lib/auth_mysql.py
#    - AUTH_MYSQL_HOST=mysql
#    - AUTH_MYSQL_USER=root
#    - AUTH_MYSQL_PASSWORD=init123!!
#    - AUTH_MYSQL_DATABASE=ejabberd
#    - AUTH_MYSQL_QUERY_GETPASS=SELECT password FROM users WHERE username = CONCAT(%(user)s, '@', %(host)s)
#    - AUTH_MYSQL_QUERY_SETPASS=UPDATE users SET password = %(password)s WHERE username = CONCAT(%(user)s, '@', %(host)s)
#    - AUTH_MYSQL_QUERY_REGISTER=INSERT INTO users ( username, password ) VALUES ( CONCAT(%(user)s, '@', %(host)s), %(password)s )
#    - AUTH_MYSQL_QUERY_UNREGISTER=DELETE FROM users WHERE username = CONCAT(%(user)s, '@', %(host)s)