mysql:
  container_name: mysql
  image: mysql
  ports:
    - 3306:3306
  volumes:
    - ./sql:/root/
## Add mysql database folder
##    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=init123!!
    - MYSQL_DATABASE=ejabberd
ejabberd:
  container_name: ejabberd
  image: knightpop/atlantis_ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  links:
    - mysql:mysql
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=localhost
    - EJABBERD_ADMINS=admin@localhost
#    - EJABBERD_USERS=admin@localhost:init123!! ktz@localhost:init123!!
    - EJABBERD_HTTPS=false
    - EJABBERD_STARTTLS=false
    - EJABBERD_AUTH_METHOD=sql
    - EJABBERD_CONFIGURE_ODBC=true
    - EJABBERD_ODBC_TYPE=mysql
    - EJABBERD_ODBC_SERVER=mysql
    - EJABBERD_ODBC_DATABASE=ejabberd
    - EJABBERD_ODBC_USERNAME=root
    - EJABBERD_ODBC_PASSWORD=init123!!