mysql:
  container_name: mysql
  image: mysql:5.7.17
  ports:
    - 3306:3306
  volumes:
    - ./sql:/root/
## Add mysql database folder
##    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=init123!!
    - MYSQL_DATABASE=ejabberd
ejabberd:
  container_name: ejabberd
  image: atlantishomeserver/atlantis_ejabberd:latest
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
    - 5281:5281
  links:
    - mysql:mysql
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=localhost
    - EJABBERD_ADMINS=admin@localhost
    - EJABBERD_HTTPS=false
    - EJABBERD_STARTTLS=false
    - EJABBERD_AUTH_METHOD=sql
    - EJABBERD_CONFIGURE_ODBC=true
    - EJABBERD_ODBC_TYPE=mysql
    - EJABBERD_ODBC_SERVER=mysql
    - EJABBERD_ODBC_DATABASE=ejabberd
    - EJABBERD_ODBC_USERNAME=root
    - EJABBERD_ODBC_PASSWORD=init123!!
    - EJABBERD_LOGLEVEL=5
radios:
  container_name: radios
  image: atlantishomeserver/radios_server:latest
  ports:
    - 9990:9990
    - 8888:8888
  links:
    - ejabberd:ejabberd